server:
  port: 8080

main-service:
  url: "http://main-service:8081"

auth-service:
  url: "http://auth-service:8082"

spring:
  application:
    name: gateway
  main:
    banner-mode: off

  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"

jwt:
  secret: "MySuperSecretKeyChangeInProduction12345WhichIsNotLessThen256BitOr64Simvols"
  expiration: 86400000